# Notebook Python SAS

## Import des données dans Python

In [1]:
import pandas as pd
# data_url = "https://forge.scilab.org/index.php/p/rdataset/source/file/master/csv/datasets/cars.csv"
data_url = "cars.csv"
df_python = pd.read_csv(data_url)
df_python.head()

   Unnamed: 0  speed  dist
0           1      4     2
1           2      4    10
2           3      7     4
3           4      7    22
4           5      8    16

Supression de la première colonne

In [2]:
df_python.drop(df_python.columns[[0]], axis=1, inplace=True)
df_python.head()

   speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16

## Summary avec Python

In [3]:
df_python.describe().transpose()

       count   mean        std  min   25%   50%   75%    max
speed   50.0  15.40   5.287644  4.0  12.0  15.0  19.0   25.0
dist    50.0  42.98  25.769377  2.0  26.0  36.0  56.0  120.0

## Summary avec SAS

In [4]:
import saspy
session_sas = saspy.SASsession(cfgname='winlocal')
df_sas = session_sas.df2sd(df_python)
df_sas

SAS Connection established. Subprocess id is 4708

Libref  = WORK
Table   = _df
Dsopts  = {}
Results = Pandas

- La fonction `df2sd()` produit un objet Python, ici `df_sas`, qui contient une table SAS nommée `_df`.
- `SASPy` fournit des objets Python de haut niveau pour les principales procédures SAS.
- Toutes les fonctions SAS sont exécutables à l'aide de la commande magique `%%SAS`.
- On applique les fonctions Python sur l'objet `df_sas` et les fonctions SAS sur l'objet `_df`.

In [5]:
df_sas.describe()

  Variable   N  NMiss  Median   Mean     StdDev  Min  P25  P50  P75  Max
0    speed  50      0      15  15.40   5.287644    4   12   15   19   25
1     dist  50      0      36  42.98  25.769377    2   26   36   56  120

In [6]:
%%SAS session_sas
ods title;
ods noproctitle;
proc means data=_df maxdec=2;
run;

## Liens utiles

**Code SAS dans notebook Jupyter :**

- https://blogs.sas.com/content/sasdummy/2016/04/24/how-to-run-sas-programs-in-jupyter-notebook/
- https://blogs.sas.com/content/sasdummy/2017/04/08/python-to-sas-saspy/
- https://sassoftware.github.io/saspy/

**Export vers pdf :**

- https://github.com/sassoftware/sas_kernel/issues/13
- https://stackoverflow.com/questions/43965823/convert-notebook-generated-html-snippet-to-latex-and-pdf
- https://github.com/jupyter/nbconvert/issues/474